### ISSUE TITLE
Does reconciler always runs twice on creation of CRD?

### ISSUE THREAD

**Issue by smartaquarius10** [leovct/kube-operator-tutorial#2]
Hello,

Hope you are doing well. Whenever I create an object belonging to the CRD, Reconciler executes twice. Is this a common behavior.

Could you please suggest. Thank you.

Kind Regards
Tanul

**Comment by leovct** [comment]
Hi @smartaquarius10, that's a super interesting question. This kind of problem can happen often and to solve them, you need to filter the type of events that can trigger the reconciliation loop.

In the context of this tutorial, the controller is super simple and I voluntarily omitted some things such as event filtering. The problem you mention is caused by the updates we perform on the `Foo` custom resources. When a reconciliation loop is performed - let's say when you create a new custom resource, often, the status of the custom resource is updated which then triggers another reconciliation loop. **To avoid this, you need to prevent the status update events to trigger reconciliation loops.**

Here's how I would solve this problem. I would add a `WithEventFilter` part and write my own `updateEventFilter` function in the `SetupWithManager` function. Note that it's also possible to write customs `createEventFilter` and `deleteEventFilter` the same way.
```go
// SetupWithManager sets up the controller with the Manager.
func (r *FooReconciler) SetupWithManager(mgr ctrl.Manager) error {
	return ctrl.NewControllerManagedBy(mgr).
		For(&tutorialv1.Foo{}).
		Watches(
			&source.Kind{Type: &corev1.Pod{}},
			handler.EnqueueRequestsFromMapFunc(r.mapPodsReqToFooReq),
		).
                WithEventFilter(predicate.Funcs{
			UpdateFunc: updateEventFilter,
		}).
		Complete(r)
}

// Custom function to filter update events.
func updateEventFilter(e event.UpdateEvent) bool {
        // Check if the generation has changed.
        // If yes, it means that the spec of the object was updated and thus we want to trigger a reconciliation loop.
       if (e.ObjectOld.GetGeneration() != e.ObjectNew.GetGeneration()) {
              return true;
       }

       // By default, do not trigger a reconciliation loop.
       return false;
}
```

**Comment by smartaquarius10** [comment]
@leovct , Oh got it.. Thank you so much. So due to status update this is happening. I have specified like this as I want to ignore the delete event completely. 

```
func ignoreDeletionPredicate() predicate.Predicate {
	return predicate.Funcs{
		UpdateFunc: func(e event.UpdateEvent) bool {
			// Ignore updates to CR status in which case metadata.Generation does not change
			return e.ObjectOld.GetGeneration() != e.ObjectNew.GetGeneration()
		},
		DeleteFunc: func(e event.DeleteEvent) bool {
			// Evaluates to false if the object has been confirmed deleted.
			return !e.DeleteStateUnknown
		},
	}
}
```
